def trial(proby):
    if proby == 13:
        print("/")
    if proby == 12:
        print("/ \ ")
    if proby == 11:
        print(" | ")
        print("/ \ ")
    if proby == 10:
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 9:
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 8:
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 7:
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 6:
        print("  _ ")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 5:
        print("  _ _")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 4:
        print("  _ _ ")
        print(" |   |")
        print(" | ")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 3:
        print("  _ _ ")
        print(" |   |")
        print(" |   O")
        print(" | ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 2:
        print("  _ _ ")
        print(" |   |")
        print(" |   O")
        print(" |  / \ ")
        print(" | ")
        print(" | ")
        print("/ \ ")
    if proby == 1:
        print("  _ _ ")
        print(" |   |")
        print(" |   O")
        print(" |  / \ ")
        print(" |   |")
        print(" | ")
        print("/ \ ")
    if proby == 0:
        print("  _ _ ")
        print(" |   |")
        print(" |   O")
        print(" |  / \ ")
        print(" |   |")
        print(" |  / \ ")
        print("/ \ ")
